### ISSUE TITLE
Remove outer scroll bar

### ISSUE THREAD

**Issue by cjshawMIT** [CLIxIndia-Dev/unplatform_v2#179]
There are an extra 5 pixels that causes the iframe (content player container) to have a scroll bar ... let's get rid of it.

**Comment by resource11** [comment]
Yes, it's some sort of browser oddity with flexbox layouts. I have a temporary workaround that seems to work in Chrome 63. FF 57, Safari 10. Will make a hotfix for now until we find the root cause.

**Comment by cjshawMIT** [comment]
I think this was closed by PR #180
