### ISSUE TITLE
Broken CSS for nav when viewing content player

### ISSUE THREAD

**Issue by cjshawMIT** [CLIxIndia-Dev/unplatform_v2#23]
<img width="986" alt="captura de pantalla 2017-02-03 a las 2 16 55 pm" src="https://cloud.githubusercontent.com/assets/4930129/22604869/7aa1b414-ea1b-11e6-8e7b-7e1a177ab9a1.png">

**Comment by pwilkins** [comment]
It isn't apparent to me how the  CSS is broken, unless it is the "Please configure your school..." message.

**Comment by cjshawMIT** [comment]
Kathleen’s going to look at this, but there’s supposed to be a shadow under the nav that visually separates the content player from the nav bar.

**Comment by resource11** [comment]
solved in PR [#123 ](https://github.com/CLIxIndia-Dev/unplatform_v2/pull/123)
