### ISSUE TITLE
CSS in Windows school configuration is off

### ISSUE THREAD

**Issue by coleshaw** [CLIxIndia-Dev/unplatform_v2#5]
Background is white, you can't see the labels, and no "current configuration" shown after you save...seen on Kirky's laptop.

**Comment by cjshawMIT** [comment]
Note that @resource11 was able to replicate this...

**Comment by resource11** [comment]
I replicated this on the mac. What I did was open localhost:8888 in a fresh tab, then manually typed in /school to the URL. The page  and text is white. But! When trying to inspect the page, the CSS loaded and everything shows. The bug isn't consistently replicable yet, though.
