### ISSUE TITLE
CSS: Session expiration page review

### ISSUE THREAD

**Issue by cjshawMIT** [CLIxIndia-Dev/unplatform_v2#50]
Currently unstyled, but might need to be. This shows up on the screen if the user's session expires due to inactivity, and asks them to navigate back to the survey page...

`templates/session_expired.html`

@resource11 @gokatgo

**Comment by cjshawMIT** [comment]
@gokatgo

**Comment by cjshawMIT** [comment]
random comment

**Comment by resource11** [comment]
This was solved in PR [#125](https://github.com/CLIxIndia-Dev/unplatform_v2/pull/123)
