### ISSUE TITLE
CSS: Background image ends

### ISSUE THREAD

**Issue by cjshawMIT** [CLIxIndia-Dev/unplatform_v2#70]
When there are a lot of lessons such that they extend lower than the size of the background (or when you shrink the screen, this forces the effect), the background image ends and you get a funky tiling effect. See screenshot.

<img width="1080" alt="captura de pantalla 2017-04-03 a las 1 30 39 pm" src="https://cloud.githubusercontent.com/assets/4930129/24622138/e9fd2396-1871-11e7-8558-fbb85e26c72e.png">

**Comment by resource11** [comment]
This was solved in PR [#123](https://github.com/CLIxIndia-Dev/unplatform_v2/pull/123)
