### ISSUE TITLE
A11Y: Review refs on `user-select` inputs

### ISSUE THREAD

**Issue by cjshawMIT** [CLIxIndia-Dev/unplatform_v2#81]
Do we need one ref per `user-select` input?

The current implementation seems to only have one ref, `inputField`:

https://github.com/CLIxIndia-Dev/unplatform_v2/blob/master/ui/src/routes/Home/components/HomeView.js#L132

```
        <input key={index}
          onChange={(e) => this._onHandleUserTypeSelect(e)}
          type="radio"
          name="userType"
          value={label}
          // tabIndex={-1}
          checked={checked}
          className="user-select__input"
          ref={(input) => { this.inputField = input; }}
          />
```

**Comment by resource11** [comment]
I believe this was solved in PR [#125](https://github.com/CLIxIndia-Dev/unplatform_v2/pull/125)
